version: '3.1'

services:
  app:
    build: .
    image: opux2
    environment:
      DOCKER_MODE: ""
      MYSQL_HOST: "mysql"
    volumes:
      - ./settings.custom.json:/app/settings.custom.json
      - ./authweb.config.json:/app/Plugins/AuthWeb/config.json
      - ./logs:/app/Logs
    ports:
      - 8090:8090
    links:
      - db:mysql
    depends_on:
      - db

  db:
    image: mariadb:10.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "opux"
      MYSQL_DATABASE: "discord"
      MYSQL_USER: "discord"
      MYSQL_PASSWORD: "password"
    volumes:
      - opux-data:/var/lib/mysql
      - ./db-healthcheck.sh:/db-healthcheck.sh
    healthcheck:
      test: ["CMD", "/db-healthcheck.sh"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  opux-data:
